# -*- coding: utf-8 -*-
"""Real-Time IoT Weather Station with MQTT and Google Colab Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SadWWGPPViRC1EeGNPchDtT7iySiQSJG
"""

# 🌤️ Real-Time IoT Weather Station Dashboard

# Step 1: Install missing dependencies
try:
    from paho.mqtt.client import Client
except ImportError:
    import sys
    !{sys.executable} -m pip install paho-mqtt
    from paho.mqtt.client import Client

import json
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import threading
import time

# MQTT Config
MQTT_BROKER = "broker.hivemq.com"
MQTT_PORT = 1883
MQTT_TOPIC = "iot/weatherstation"

# Data Storage
temperature_data = []
humidity_data = []
timestamps = []

# Lock for thread safety
data_lock = threading.Lock()

# Callback: on connect
def on_connect(client, userdata, flags, rc):
    print("✅ Connected to broker with result code", rc)
    client.subscribe(MQTT_TOPIC)

# Callback: on message
def on_message(client, userdata, msg):
    try:
        payload = json.loads(msg.payload.decode())
        temp = float(payload["temperature"])
        hum = float(payload["humidity"])
        timestamp = datetime.now()

        with data_lock:
            temperature_data.append(temp)
            humidity_data.append(hum)
            timestamps.append(timestamp)

        print(f"📥 Received: Temp={temp}°C, Hum={hum}%, Time={timestamp.strftime('%H:%M:%S')}")

    except Exception as e:
        print("❌ Error parsing message:", e)

# Start MQTT client
def start_mqtt():
    client = Client()
    client.on_connect = on_connect
    client.on_message = on_message
    client.connect(MQTT_BROKER, MQTT_PORT, 60)
    client.loop_forever()

# Live plotting function
def plot_data():
    plt.ion()
    fig, ax = plt.subplots(figsize=(10, 5))

    while True:
        plt.cla()

        with data_lock:
            if len(timestamps) > 0:
                df = pd.DataFrame({
                    "Time": timestamps,
                    "Temperature": temperature_data,
                    "Humidity": humidity_data
                })
                df.set_index("Time", inplace=True)
                df.plot(ax=ax)

                plt.title("📊 Live Temperature & Humidity")
                plt.xlabel("Time")
                plt.ylabel("Value")
                plt.grid(True)
                plt.legend(loc="upper left")

        plt.pause(5)

# Main
if __name__ == "__main__":
    print("🚀 Starting IoT Weather Station Dashboard...")

    mqtt_thread = threading.Thread(target=start_mqtt)
    mqtt_thread.daemon = True
    mqtt_thread.start()

    try:
        plot_data()
    except KeyboardInterrupt:
        print("\n🛑 Stopped by user.")